---
title: Ressources
sidebar: false
lang: fr
---

Vous pouvez télécharger le `.bib` contenant toutes les références citées pendant la formation en cliquant sur le bouton ci-dessous.

<p><a href="./files/bib/references.bib" class="btn btn-success" role="button">{{< fa download >}} fichier .bib contenant toutes les références </a></p>

## Livre conseillé : Statistical Rethinking

> Richard McElreath, *Statistical Rethinking: A Bayesian Course with Examples in R and Stan*. Second Edition. CRC Press [@McElreath:2020].

Liens officiels :

- {{< fa book >}} [Book page](https://xcelab.net/rm/statistical-rethinking/)
- {{< fa brands r-project >}} [R package](https://github.com/rmcelreath/rethinking)
- {{< fa brands youtube >}} [2022 lecture videos](https://www.youtube.com/playlist?list=PLDcUM9US4XdMROZ57-OIRtIK0aOynbgZN)
- {{< fa brands github >}} [2022 lecture slides and homework and answers](https://github.com/rmcelreath/stat_rethinking_2022)

Traduction avec `tidyverse` et `brms` (en ligne) :

- {{< fa laptop-code >}} A. Solomon Kurz, [*Statistical Rethinking with brms, ggplot2, and the tidyverse: Second edition*](https://bookdown.org/content/4857/) [@Kurz:2021]
- {{< fa laptop-code >}} Vincent Arel-Bundock, [*Statistical Rethinking 2 with Stan and R*](https://vincentarelbundock.github.io/rethinking2/), [@Arel-Bundock:2020]

## Autres livres

Quelques autres suggestions de lecture sur lesquelles je me suis appuyé pour préparer ce cours.

- {{< fa book >}} John K. Kruschke, *Doing Bayesian Data Analysis: A Tutorial with R, JAGS, and Stan* [@Kruschke:2015]
- {{< fa book >}} Ben Lambert, *A Student’s Guide to Bayesian Statistics* [@Lambert:2018]
- {{< fa book >}} Andrew Gelman, John Carlin, Hal Stern, David Dunson, Aki Vehtari, and Donald Rubin, *Bayesian Data Analysis* [@GelmanCarlinStern:2013]
- {{< fa book >}} Allen B. Downey, [*Think Bayes 2*](https://allendowney.github.io/ThinkBayes2/) [@Downey:2021]
- {{< fa book >}} Nicenboim, B., Schad, D., & Vasishth, S. (2021). An Introduction to Bayesian Data Analysis for Cognitive Science. Available [online](https://vasishth.github.io/bayescogsci/book/).
