# (APPENDIX) Annexes {-}

# Glossaire {#glossaire}

**Affirmation du conséquent** : Raisonnement fallacieux qui consiste à inférer la réalisation d’un antécédent sur la base de la réalisation du conséquent.

**Facteur de Bayes (*Bayes factor*)** : Support relatif fourni par un jeu de données pour deux hypothèses alternatives. Si on considère deux hypothèses $\mathcal{H}_{1}$ et $\mathcal{H}_{2}$ et des données $x$, alors le facteur de Bayes est $p(x \ | \ \mathcal{H}_{1}) / p(x \ | \ \mathcal{H}_{2})$. Ce dernier peut-être inteprêté comme un "facteur de mise à jour" du rapport des chances a priori (i.e., avant de prendre connaissance des données) vers le rapport des chances a posteriori (i.e., après avoir pris connaissance des données).

**Négation de l'antécédent** : Raisonnement fallacieux qui consiste à affirmer une négation du conséquent sur la base d’une négation de l’antécédent.

**Probabilité** : Une valeur numérique comprise entre 0 et 1 respectant les règles du calcul probabiliste (cf. Chapitre 1).

**Règle de la somme**: Pour deux événements $A$ et $B$, la règle de la somme nous dit que : $\Pr(A \cup B) = \Pr(A) + \Pr(B) - \Pr(A \cap B)$.

**Règle du produit**: Pour deux événements $A$ et $B$, la règle du produit nous dit que : $\Pr(A, B) = \Pr(B) \cdot \Pr(A \ | \ B) = \Pr(A) \cdot \Pr(B \ | \ A)$.

**Vraisemblance (*Likelihood*)** : Une mesure du support fourni par les données pour certaines valeurs de paramètres. Après avoir observé des donnés $x$, la vraisemblance d'un paramètre $\theta$ est proportionnelle à $p(x \ | \ \theta)$.
